/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYahooRouteImport } from './routes/api.yahoo'
import { Route as ApiAuthRouteImport } from './routes/api.auth'
import { Route as ApiAuthRefreshRouteImport } from './routes/api.auth.refresh'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYahooRoute = ApiYahooRouteImport.update({
  id: '/api/yahoo',
  path: '/api/yahoo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRefreshRoute = ApiAuthRefreshRouteImport.update({
  id: '/refresh',
  path: '/refresh',
  getParentRoute: () => ApiAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/yahoo': typeof ApiYahooRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/yahoo': typeof ApiYahooRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/auth': typeof ApiAuthRouteWithChildren
  '/api/yahoo': typeof ApiYahooRoute
  '/api/auth/refresh': typeof ApiAuthRefreshRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/auth' | '/api/yahoo' | '/api/auth/refresh'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/auth' | '/api/yahoo' | '/api/auth/refresh'
  id: '__root__' | '/' | '/api/auth' | '/api/yahoo' | '/api/auth/refresh'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAuthRoute: typeof ApiAuthRouteWithChildren
  ApiYahooRoute: typeof ApiYahooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/yahoo': {
      id: '/api/yahoo'
      path: '/api/yahoo'
      fullPath: '/api/yahoo'
      preLoaderRoute: typeof ApiYahooRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/refresh': {
      id: '/api/auth/refresh'
      path: '/refresh'
      fullPath: '/api/auth/refresh'
      preLoaderRoute: typeof ApiAuthRefreshRouteImport
      parentRoute: typeof ApiAuthRoute
    }
  }
}

interface ApiAuthRouteChildren {
  ApiAuthRefreshRoute: typeof ApiAuthRefreshRoute
}

const ApiAuthRouteChildren: ApiAuthRouteChildren = {
  ApiAuthRefreshRoute: ApiAuthRefreshRoute,
}

const ApiAuthRouteWithChildren =
  ApiAuthRoute._addFileChildren(ApiAuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAuthRoute: ApiAuthRouteWithChildren,
  ApiYahooRoute: ApiYahooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
